export * from './lib/tire-storage-tsm-services/tire-storage-tsm-services.component'
export { CustomersService } from './lib/service/customers.service'
export { CustomersMetadataService } from './lib/service/customers-metadata.service'
export * from './lib/models/customer.model'
export * from './lib/models/customer-metadata.model'
